spring.application.name=smartcityportal
spring.datasource.url=jdbc:postgresql://ep-cold-mouse-atqjt426-pooler.c-9.us-east-1.aws.neon.tech/smartcity?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NU4fqeV0Elby
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=56tghtygvhjcyuuujhuykt-is-at-least-32-characters-long-123456
jwt.expiration=86400000